// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace HolyAngels.Web.Controllers {
    public partial class HomeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string About = "About";
            public readonly string Contact = "Contact";
            public readonly string Mural = "Mural";
            public readonly string History = "History";
            public readonly string Mission = "Mission";
            public readonly string Christianity = "Christianity";
            public readonly string Privacy = "Privacy";
            public readonly string Terms = "Terms";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string About = "~/Views/Home/About.cshtml";
            public readonly string Christianity = "~/Views/Home/Christianity.cshtml";
            public readonly string Contact = "~/Views/Home/Contact.cshtml";
            public readonly string History = "~/Views/Home/History.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Mission = "~/Views/Home/Mission.cshtml";
            public readonly string Mural = "~/Views/Home/Mural.cshtml";
            public readonly string Privacy = "~/Views/Home/Privacy.cshtml";
            public readonly string Terms = "~/Views/Home/Terms.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_HomeController: HolyAngels.Web.Controllers.HomeController {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult About() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.About);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Contact() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Contact);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Mural() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Mural);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult History() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.History);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Mission() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Mission);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Christianity() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Christianity);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Privacy() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Privacy);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Terms() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Terms);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
